# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Sy Chan
title: MIT Sloan MBA 2020 candidate
email: hksychan@mit.edu
website: hksychan.github.io

# Social links
#twitter_username: facespics
github_username:  hksychan
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: sychan82
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: image/gprofile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sy and I'm currently an MBA 2020 candidate at MIT Sloan School of Management. 

  I am most skilled in: <mark>investment</mark>, <mark>karaoke</mark> and <mark>cooking curry</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Table Tennis
   - Gaming
   - Marathon

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
